<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="W-7FM3M13" failures="1" tests="1" name="Platform Sign Up" time="69.604" errors="0" timestamp="2020-11-04T13:33:14 IST">
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="67.821">
    <failure type="java.lang.AssertionError" message="Success Message does not exist">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:193)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
</testsuite> <!-- Platform Sign Up -->
