<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="W-7FM3M13" failures="3" tests="6" name="com.test.testcases.PlatformSignUpTest" time="290.685" errors="0" timestamp="2020-11-18T18:12:00 IST" skipped="3">
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="57.150">
    <skipped/>
  </testcase> <!-- signUpConversationalAI -->
  <system-out/>
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="40.809">
    <skipped/>
  </testcase> <!-- signUpConversationalAI -->
  <system-out/>
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="55.301">
    <failure message="Success Message does not exist" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
  <system-out/>
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="41.875">
    <failure message="Success Message does not exist" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
  <system-out/>
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="41.782">
    <failure message="Success Message does not exist" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
  <system-out/>
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="53.768">
    <skipped/>
  </testcase> <!-- signUpConversationalAI -->
  <system-out/>
</testsuite> <!-- com.test.testcases.PlatformSignUpTest -->
