<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="6" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-18T18:06:48 IST" name="Platform Suite" finished-at="2020-11-18T18:11:40 IST" duration-ms="291642">
    <groups>
    </groups>
    <test started-at="2020-11-18T18:06:48 IST" name="Platform Sign Up" finished-at="2020-11-18T18:11:40 IST" duration-ms="291642">
      <class name="com.test.testcases.PlatformSignUpTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:06:28 IST" name="beforeSuite" finished-at="2020-11-18T18:06:48 IST" duration-ms="20258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:06:49 IST" name="beforeMethod" finished-at="2020-11-18T18:06:49 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method retried="true" signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:06:49 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-18T18:07:43 IST" duration-ms="53652" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ramarajan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sampath]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[testdqefewfewf@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:07:43 IST" name="afterMethod" finished-at="2020-11-18T18:07:44 IST" duration-ms="795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:07:44 IST" name="beforeMethod" finished-at="2020-11-18T18:07:44 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:07:44 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-18T18:08:25 IST" duration-ms="41694" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ramarajan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sampath]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[testdqefewfewf@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:08:25 IST" name="afterMethod" finished-at="2020-11-18T18:08:26 IST" duration-ms="181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method retried="true" signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:08:26 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-18T18:09:06 IST" duration-ms="40686" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sachin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tendulkar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test1@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:08:26 IST" name="beforeMethod" finished-at="2020-11-18T18:08:26 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:09:06 IST" name="afterMethod" finished-at="2020-11-18T18:09:07 IST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:09:07 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-18T18:09:48 IST" duration-ms="41666" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sachin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tendulkar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test1@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:09:07 IST" name="beforeMethod" finished-at="2020-11-18T18:09:07 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:09:48 IST" name="afterMethod" finished-at="2020-11-18T18:09:48 IST" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:09:48 IST" name="beforeMethod" finished-at="2020-11-18T18:09:48 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method retried="true" signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:09:48 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-18T18:10:45 IST" duration-ms="56893" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gilg]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test3@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:10:45 IST" name="afterMethod" finished-at="2020-11-18T18:10:45 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:10:45 IST" name="beforeMethod" finished-at="2020-11-18T18:10:45 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:10:45 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-18T18:11:40 IST" duration-ms="54502" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gilg]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test3@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:11:40 IST" name="afterMethod" finished-at="2020-11-18T18:11:40 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.test.testcases.PlatformSignUpTest@a2431d0]" started-at="2020-11-18T18:11:40 IST" name="afterSuite" finished-at="2020-11-18T18:12:00 IST" duration-ms="20026" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.testcases.PlatformSignUpTest -->
    </test> <!-- Platform Sign Up -->
  </suite> <!-- Platform Suite -->
</testng-results>
